version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "maro114510"
    cooldown:
      default-days: 5
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
